[dependencies]
base = "0.12.0"

[package]
name = "xtended-random"
version = "1.0.0"
description = "A library for random helper funtions"
repository = "https://github.com/edjcase/motoko_random"
keywords = [ "random", "pseudo" ]
license = "MIT"

[dev-dependencies]
test = "2.0.0"
